version: "3.9"

services:
  cpp:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - ..:/workspaces/cpp
    # This is where ports would go
    networks:
      - cpp-network
  # Additional services here
# volumes here
networks:
  cpp-network:
    driver: bridge
